Clang: fix build
Since Windows DLL patch, SystemC build with Clang
is broken with errors like:

src/sysc/utils/sc_temporary.h:176:37: error: allocation of incomplete type 'sc_dt::sc_unsigned_bitref'
src/sysc/utils/sc_temporary.h:191:14: error: subscript of pointer to incomplete type 'sc_dt::sc_unsigned_bitref'
[...]

This commit fixes build with Clang ensuring explicit
template instantiations are done after complete
declaration of used types.

Signed-off-by: Guillaume Delbergue <guillaume.delbergue@greensocs.com>