sc_main_main.cpp: fix copying of command-line args
When initializing the local copy of the argv vector in
`sc_elab_and_sim`, the wrong constructor overload is
selected by GCC (4.9.3) on Linux, 32-bit.

To help the compiler selecting the correct constructor
overload, add a `static_cast<char*>` to the `NULL`
constant.

No functional changes.

Detailed error message:
```
In file included from .../gcc/4.9.3/include/c++/4.9.3/vector:64:0,
                 from ../../../src/sysc/kernel/sc_cmnhdr.h:149,
                 from ../../../src/sysc/kernel/sc_main_main.cpp:31:
.../gcc/4.9.3/include/c++/4.9.3/bits/stl_vector.h: In instantiation of 'void std::vector<_Tp, _Alloc>::_M_initialize_dispatch(_Integer, _Integer, std::__true_type) [with _Integer = int; _Tp = char*; _Alloc = std::allocator<char*>]':
.../gcc/4.9.3/include/c++/4.9.3/bits/stl_vector.h:413:55:   required from 'std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = int; _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<char*>]'
../../../src/sysc/kernel/sc_main_main.cpp:73:48:   required from here
.../gcc/4.9.3/include/c++/4.9.3/bits/stl_vector.h:1252:59: error: invalid conversion from 'int' to 'std::vector<char*>::value_type {aka char*}' [-fpermissive]
    _M_fill_initialize(static_cast<size_type>(__n), __value);
                                                           ^
.../gcc/4.9.3/include/c++/4.9.3/bits/stl_vector.h:1298:7: note: initializing argument 2 of 'void std::vector<_Tp, _Alloc>::_M_fill_initialize(std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = char*; _Alloc = std::allocator<char*>; std::vector<_Tp, _Alloc>::size_type = unsigned int; std::vector<_Tp, _Alloc>::value_type = char*]'
       _M_fill_initialize(size_type __n, const value_type& __value)
```