sc_vector: Allow initialization from external SystemC context
IEEE 1666-2011 requires proper sc_vector elements creation in the
SystemC hierarchy, quoting clause 8.5.5:

  The newly created object shall have the same parent as the vector;
  that is, the elements of a vector shall be siblings of the vector
  object itself in the SystemC object hierarchy.

There is no restriction to the invocation context of the init function
listed in that (or any other sc_vector) clause in 1666-2011.

Previously, the sc_vector implementation did not allow calling init()
from outside the owning module/process' constructor or initialization
callback and reported an error like:

   Error: (E806) sc_vector::init called from invalid object context: ...

This patch lifts this restriction by explicitly enforcing the correct
context during sc_vector<T>::init.