sc_trace_file_base.cpp: fix warning on GCC <= 4.3 (32-bit)
.../sc_trace_file_base.cpp:280: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:281: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:303: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:304: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:305: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:306: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:307: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:308: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:309: error: integer constant is too large for 'long' type
.../sc_trace_file_base.cpp:310: error: integer constant is too large for 'long' type

To work around this issue, mark constants as 64-bit explicitly by using the
platform-specific suffixes.  The UINT64_C macro snippet has been copied from
sc_int_mask.cpp, where it has been used before already.